#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Welcome banner
clear
echo -e "${BLUE}${BOLD}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                                                           ║"
echo "║        Contentful Live Preview - Setup Wizard            ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

# Check if .env.local already exists
if [ -f .env.local ]; then
  echo -e "${YELLOW}⚠️  Warning: .env.local already exists!${NC}"
  echo ""
  read -p "Do you want to create a backup and continue? (y/n): " -n 1 -r
  echo ""
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    BACKUP_FILE=".env.local.backup.$(date +%Y%m%d_%H%M%S)"
    cp .env.local "$BACKUP_FILE"
    echo -e "${GREEN}✓ Backup created: $BACKUP_FILE${NC}"
    echo ""
  else
    echo -e "${RED}Setup cancelled.${NC}"
    exit 1
  fi
fi

# Introduction
echo -e "${BOLD}This wizard will help you configure your Contentful credentials.${NC}"
echo ""
echo "You'll need to provide:"
echo "  1. Contentful Space ID"
echo "  2. Content Delivery API Token (for published content)"
echo "  3. Content Preview API Token (for draft content)"
echo "  4. Preview Secret (any random string for security)"
echo "  5. Environment name (optional, defaults to 'master')"
echo ""
echo -e "${BLUE}ℹ️  Find these credentials in your Contentful space:${NC}"
echo "   Settings → API keys → Your API key"
echo ""
read -p "Press Enter to continue..."
echo ""

# Function to read input with validation
read_required() {
  local prompt="$1"
  local var_name="$2"
  local value=""
  
  while [ -z "$value" ]; do
    read -p "$prompt: " value
    if [ -z "$value" ]; then
      echo -e "${RED}✗ This field is required. Please try again.${NC}"
    fi
  done
  
  eval "$var_name='$value'"
}

read_optional() {
  local prompt="$1"
  local var_name="$2"
  local default="$3"
  local value=""
  
  read -p "$prompt [${default}]: " value
  if [ -z "$value" ]; then
    value="$default"
  fi
  
  eval "$var_name='$value'"
}

# Collect credentials
echo -e "${BOLD}Step 1: Contentful Space Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read_required "Contentful Space ID" SPACE_ID
echo -e "${GREEN}✓${NC}"
echo ""

read_optional "Environment" ENVIRONMENT "master"
echo -e "${GREEN}✓${NC}"
echo ""

echo -e "${BOLD}Step 2: API Tokens${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read_required "Content Delivery API Token" DELIVERY_TOKEN
echo -e "${GREEN}✓${NC}"
echo ""

read_required "Content Preview API Token" PREVIEW_TOKEN
echo -e "${GREEN}✓${NC}"
echo ""

echo -e "${BOLD}Step 3: Security${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The preview secret is used to secure the preview API endpoint."
echo "This can be any random string (e.g., a UUID or random password)."
echo ""

read_optional "Preview Secret" PREVIEW_SECRET "$(openssl rand -hex 32 2>/dev/null || echo 'change-this-to-a-random-secret')"
echo -e "${GREEN}✓${NC}"
echo ""

# Confirmation
echo ""
echo -e "${BOLD}Configuration Summary:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Space ID:           $SPACE_ID"
echo "Environment:        $ENVIRONMENT"
echo "Delivery Token:     ${DELIVERY_TOKEN:0:10}...${DELIVERY_TOKEN: -4}"
echo "Preview Token:      ${PREVIEW_TOKEN:0:10}...${PREVIEW_TOKEN: -4}"
echo "Preview Secret:     ${PREVIEW_SECRET:0:10}...${PREVIEW_SECRET: -4}"
echo ""
read -p "Does this look correct? (y/n): " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo -e "${RED}Setup cancelled. Run ./install.sh again to restart.${NC}"
  exit 1
fi

# Create .env.local file
echo ""
echo -e "${BLUE}Creating .env.local file...${NC}"

cat > .env.local << EOL
# Contentful Configuration
# Generated by install.sh on $(date)

# Space Configuration
CONTENTFUL_SPACE_ID=${SPACE_ID}
CONTENTFUL_ENVIRONMENT=${ENVIRONMENT}

# API Tokens
CONTENTFUL_DELIVERY_TOKEN=${DELIVERY_TOKEN}
CONTENTFUL_PREVIEW_TOKEN=${PREVIEW_TOKEN}

# Preview API Security
# This secret is used to validate preview API requests
CONTENTFUL_PREVIEW_SECRET=${PREVIEW_SECRET}

# Public Environment Variables
# These are exposed to the browser (NEXT_PUBLIC_ prefix)
NEXT_PUBLIC_CONTENTFUL_SPACE_ID=${SPACE_ID}
NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=${ENVIRONMENT}
EOL

echo -e "${GREEN}✓ .env.local created successfully!${NC}"
echo ""

# Next steps
echo -e "${BOLD}🎉 Setup Complete!${NC}"
echo ""
echo -e "${BOLD}Next Steps:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Install dependencies:"
echo -e "   ${YELLOW}npm install${NC}"
echo "   or"
echo -e "   ${YELLOW}yarn install${NC}"
echo ""
echo "2. Start the development server:"
echo -e "   ${YELLOW}npm run dev${NC}"
echo "   or"
echo -e "   ${YELLOW}yarn dev${NC}"
echo ""
echo "3. Open your browser:"
echo -e "   ${BLUE}http://localhost:3000${NC}"
echo ""
echo "4. Enable preview mode in Contentful:"
echo "   • Go to Settings → Content preview"
echo "   • Add a new content preview:"
echo -e "     Name:        ${YELLOW}Local Preview${NC}"
echo -e "     URL:         ${YELLOW}http://localhost:3000/api/preview?secret=${PREVIEW_SECRET}&slug={entry.fields.slug}${NC}"
echo ""
echo -e "${GREEN}${BOLD}Happy content browsing! 🚀${NC}"
echo ""

# Make the script executable (for next time)
chmod +x install.sh
